import type { JobPreferences, Profile, Settings } from "./types";

export const DEFAULT_SETTINGS: Settings = {
  highlightFilled: true,
  autoCoverLetter: false,
  provider: "gemini",
  rulesFirst: true,
  preferredWorkMode: "remote",
  minSalary: "",
  targetRoles: "",
};

export const DEFAULT_PROFILE: Profile = {
  firstName: null,
  lastName: null,
  fullName: null,
  email: null,
  phone: null,
  alternatePhone: null,
  city: null,
  state: null,
  country: null,
  pinCode: null,
  dateOfBirth: null,
  gender: null,
  linkedin: null,
  github: null,
  portfolio: null,
  currentDesignation: null,
  currentCompany: null,
  totalExperience: null,
  currentCTC: null,
  expectedCTC: null,
  noticePeriod: null,
  preferredLocations: null,
  workMode: null,
  summary: null,
  primarySkills: null,
  secondarySkills: null,
  programmingLanguages: null,
  spokenLanguages: null,
  fathersName: null,
  maritalStatus: null,
  nationality: null,
  category: null,
  differentlyAbled: null,
  permanentAddress: null,
  currentAddress: null,
  experiences: [],
  education: [],
  certifications: [],
  projects: [],
  achievements: [],
};

export const DEFAULT_PREFERENCES: JobPreferences = {
  roles: [],
  locations: [],
  workMode: "remote",
  minSalary: "",
  dealbreakers: [],
};
